package xml

import (
	"encoding/xml"
	"fmt"
	"strings"
	"time"
)

// CPRequest XML builder for Austrian EDA CustomerProcesses.
//
// Namespace references (version 01.40):
//
//	CPRequest: http://www.ebutilities.at/schemata/customerprocesses/cprequest/01p40
//	CommonTypes: http://www.ebutilities.at/schemata/customerprocesses/common/types/01p20
//
// NOTE: Verify the exact namespace version and element names against the XSD
// schemas from ebutilities.at before going live with a real Netzbetreiber.
//
// Supported process codes (MessageCode):
//
//	EC_REQ_ONL    — Online-Anmeldeanforderung (initial registration request)
//	EC_EINZEL_ANM — Einzelanmeldung Zählpunkt zur EG
//	EC_EINZEL_ABM — Einzelabmeldung Zählpunkt aus EG
//	EC_PRTFACT_CHG — Teilnahmefaktor ändern

const (
	cpRequestNS   = "http://www.ebutilities.at/schemata/customerprocesses/cprequest/01p40"
	cpDocumentNS  = "http://www.ebutilities.at/schemata/customerprocesses/cpdocument/01p40"
	cpCommonNS    = "http://www.ebutilities.at/schemata/customerprocesses/common/types/01p20"
	cpSchemaVer   = "01.40"
	cpDateLayout  = "2006-01-02"
	cpDateTimeLayout = "2006-01-02T15:04:05"
)

// CPRequestParams holds all parameters for building a CPRequest XML message.
type CPRequestParams struct {
	// Routing
	From           string    // sender ECNumber (EEG's MarktpartnerID)
	To             string    // receiver ECNumber (Netzbetreiber)
	GemeinschaftID string    // EC number / community ID
	Process        string    // MessageCode: EC_REQ_ONL, EC_EINZEL_ANM, EC_EINZEL_ABM, EC_PRTFACT_CHG

	// Message identifiers (generated by caller)
	MessageID      string
	ConversationID string

	// Process-specific data
	Zaehlpunkt          string    // MeteringPoint (AT...)
	ValidFrom           time.Time // date from which the change takes effect
	ShareType           string    // GC, RC_R, RC_L, CC — for ANM only
	ParticipationFactor float64   // 0..100 — for ANM and PRTFACT_CHG (0 = omit)
}

// BuildCPRequest builds an outbound CPRequest XML message for energy community processes.
func BuildCPRequest(p CPRequestParams) (string, error) {
	if p.From == "" {
		return "", fmt.Errorf("From (Marktpartner-ID) is required")
	}
	if p.To == "" {
		return "", fmt.Errorf("To (Netzbetreiber-ID) is required")
	}
	if p.GemeinschaftID == "" {
		return "", fmt.Errorf("GemeinschaftID is required")
	}
	if p.Process == "" {
		return "", fmt.Errorf("Process (MessageCode) is required")
	}
	if p.Zaehlpunkt == "" {
		return "", fmt.Errorf("Zaehlpunkt (MeteringPoint) is required")
	}
	if p.MessageID == "" || p.ConversationID == "" {
		return "", fmt.Errorf("MessageID and ConversationID are required")
	}

	now := time.Now()
	doc := cpRequestXML{
		NS:    cpRequestNS,
		NSct:  cpCommonNS,
		NSxsi: xsiNS,
		MarketDir: cpMarketDirXML{
			DocumentMode:  "PROD",
			SchemaVersion: cpSchemaVer,
			RoutingHeader: cpRoutingHeaderXML{
				Sender:   cpMessageAddressXML{AddressType: "ECNumber", Value: p.From},
				Receiver: cpMessageAddressXML{AddressType: "ECNumber", Value: p.To},
				DocumentCreationDateTime: formatDocCreationDateTime(now),
			},
			Sector:      "01",
			MessageCode: p.Process,
		},
		ProcessDir: cpProcessDirXML{
			MessageID:     p.MessageID,
			ConversationID: p.ConversationID,
			ProcessDate:   now.Format(cpDateLayout),
			MeteringPoint: p.Zaehlpunkt,
			CommunityID:   p.GemeinschaftID,
		},
	}

	// Set process-specific optional fields.
	switch p.Process {
	case "EC_REQ_ONL", "EC_EINZEL_ANM":
		if p.ShareType != "" {
			doc.ProcessDir.ShareType = p.ShareType
		}
		if p.ParticipationFactor > 0 {
			f := p.ParticipationFactor
			doc.ProcessDir.ParticipationFactor = &f
		}
		if !p.ValidFrom.IsZero() {
			s := p.ValidFrom.Format(cpDateLayout)
			doc.ProcessDir.ValidFrom = s
		}
	case "EC_EINZEL_ABM":
		if !p.ValidFrom.IsZero() {
			s := p.ValidFrom.Format(cpDateLayout)
			doc.ProcessDir.ValidFrom = s
		}
	case "EC_PRTFACT_CHG":
		if p.ParticipationFactor > 0 {
			f := p.ParticipationFactor
			doc.ProcessDir.ParticipationFactor = &f
		}
		if !p.ValidFrom.IsZero() {
			s := p.ValidFrom.Format(cpDateLayout)
			doc.ProcessDir.ValidFrom = s
		}
	}

	out, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("xml.Marshal: %w", err)
	}
	return xml.Header + string(out), nil
}

// ── XML marshal structs ───────────────────────────────────────────────────

type cpRequestXML struct {
	XMLName    xml.Name         `xml:"cp:CPRequest"`
	NS         string           `xml:"xmlns:cp,attr"`
	NSct       string           `xml:"xmlns:ct,attr"`
	NSxsi      string           `xml:"xmlns:xsi,attr"`
	MarketDir  cpMarketDirXML   `xml:"cp:MarketParticipantDirectory"`
	ProcessDir cpProcessDirXML  `xml:"cp:ProcessDirectory"`
}

type cpMarketDirXML struct {
	DocumentMode  string              `xml:"DocumentMode,attr"`
	SchemaVersion string              `xml:"SchemaVersion,attr"`
	RoutingHeader cpRoutingHeaderXML  `xml:"ct:RoutingHeader"`
	Sector        string              `xml:"ct:Sector"`
	MessageCode   string              `xml:"cp:MessageCode"`
}

type cpRoutingHeaderXML struct {
	Sender   cpMessageAddressXML `xml:"ct:Sender"`
	Receiver cpMessageAddressXML `xml:"ct:Receiver"`
	DocumentCreationDateTime string `xml:"ct:DocumentCreationDateTime"`
}

type cpMessageAddressXML struct {
	AddressType string `xml:"AddressType,attr"`
	Value       string `xml:"ct:MessageAddress"`
}

type cpProcessDirXML struct {
	MessageID           string   `xml:"ct:MessageId"`
	ConversationID      string   `xml:"ct:ConversationId"`
	ProcessDate         string   `xml:"ct:ProcessDate"`
	MeteringPoint       string   `xml:"ct:MeteringPoint"`
	CommunityID         string   `xml:"cp:CommunityID,omitempty"`
	ShareType           string   `xml:"cp:ShareType,omitempty"`
	ParticipationFactor *float64 `xml:"cp:ParticipationFactor,omitempty"`
	ValidFrom           string   `xml:"cp:ValidFrom,omitempty"`
}

// ── CPRequest 01.12 (ANFORDERUNG_PT / EC_REQ_PT) ─────────────────────────────
//
// Process CR_REQ_PT (04.10) uses schema CPRequest 01.12.
// Key differences from 01.40:
//   - Namespace: cprequest/01p12
//   - MessageCode: ANFORDERUNG_PT
//   - MarketParticipantDirectory requires Duplicate attribute
//   - ProcessDirectory has no CommunityID; date range goes in Extension
//   - DateTimeFrom/DateTimeTo use ct:DateTimeU: Austrian local time with +01:00/+02:00
//   - MessageId/ConversationId: alphanumeric only (no hyphens)
//   - AssumptionOfCosts is required in Extension

const cpRequest12NS  = "http://www.ebutilities.at/schemata/customerprocesses/cprequest/01p12"
const cpSchemaVer12  = "01.12"

// viennaLoc is used to format ct:DateTimeU values in Austrian local time.
var viennaLoc = func() *time.Location {
	loc, err := time.LoadLocation("Europe/Vienna")
	if err != nil {
		loc = time.FixedZone("CET", 3600) // fallback to UTC+1
	}
	return loc
}()

// formatDocCreationDateTime formats a time.Time as ct:DocumentCreationDateTime:
//
//	YYYY-MM-DDTHH:MM:SS+0H:00  (Austrian local time, full seconds, +01:00 or +02:00)
func formatDocCreationDateTime(t time.Time) string {
	vt := t.In(viennaLoc)
	_, offsetSec := vt.Zone()
	offsetHour := offsetSec / 3600
	return fmt.Sprintf("%s+0%d:00", vt.Format("2006-01-02T15:04:05"), offsetHour)
}

// formatDateTimeU formats a time.Time as ct:DateTimeU:
//
//	YYYY-MM-DDTHH:MM:00+0H:00  (Austrian local time, only +01:00 or +02:00)
func formatDateTimeU(t time.Time) string {
	vt := t.In(viennaLoc)
	_, offsetSec := vt.Zone()
	offsetHour := offsetSec / 3600
	return fmt.Sprintf("%s+0%d:00", vt.Format("2006-01-02T15:04:00"), offsetHour)
}

// AnforderungPTParams holds parameters for an ANFORDERUNG_PT request.
type AnforderungPTParams struct {
	From           string
	To             string
	MessageID      string    // UUID; hyphens are stripped automatically
	ConversationID string    // UUID; hyphens are stripped automatically
	Zaehlpunkt     string
	DateFrom       time.Time // start of requested data period (Austrian time)
	DateTo         time.Time // end of requested data period (Austrian time)
}

// BuildAnforderungPT builds a CPRequest 01.12 message with MessageCode=ANFORDERUNG_PT
// for requesting historical meter point data (EC_REQ_PT / CR_REQ_PT 04.10).
func BuildAnforderungPT(p AnforderungPTParams) (string, error) {
	if p.From == "" {
		return "", fmt.Errorf("From (Marktpartner-ID) is required")
	}
	if p.To == "" {
		return "", fmt.Errorf("To (Netzbetreiber-ID) is required")
	}
	if p.Zaehlpunkt == "" {
		return "", fmt.Errorf("Zaehlpunkt (MeteringPoint) is required")
	}
	if p.MessageID == "" || p.ConversationID == "" {
		return "", fmt.Errorf("MessageID and ConversationID are required")
	}

	// ct:GroupingId pattern: [0-9A-Za-z]* — hyphens not allowed, max 35 chars
	msgID  := strings.ReplaceAll(p.MessageID, "-", "")
	convID := strings.ReplaceAll(p.ConversationID, "-", "")
	if len(msgID) > 35 {
		msgID = msgID[:35]
	}
	if len(convID) > 35 {
		convID = convID[:35]
	}

	now := time.Now()
	doc := cpRequest12XML{
		NS:    cpRequest12NS,
		NSct:  cpCommonNS,
		NSxsi: xsiNS,
		MarketDir: cpMarketDir12XML{
			DocumentMode:  "PROD",
			Duplicate:     "false",
			SchemaVersion: cpSchemaVer12,
			RoutingHeader: cpRoutingHeaderXML{
				Sender:                   cpMessageAddressXML{AddressType: "ECNumber", Value: p.From},
				Receiver:                 cpMessageAddressXML{AddressType: "ECNumber", Value: p.To},
				DocumentCreationDateTime: formatDocCreationDateTime(now),
			},
			Sector:      "01",
			MessageCode: "ANFORDERUNG_PT",
		},
		ProcessDir: cpProcessDir12XML{
			MessageID:      msgID,
			ConversationID: convID,
			ProcessDate:    now.Format(cpDateLayout),
			MeteringPoint:  p.Zaehlpunkt,
			Extension: &cpExtension12XML{
				DateTimeFrom:      formatDateTimeU(p.DateFrom),
				DateTimeTo:        formatDateTimeU(p.DateTo),
				AssumptionOfCosts: false,
			},
		},
	}

	out, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("xml.Marshal: %w", err)
	}
	return xml.Header + string(out), nil
}

type cpRequest12XML struct {
	XMLName    xml.Name          `xml:"cp:CPRequest"`
	NS         string            `xml:"xmlns:cp,attr"`
	NSct       string            `xml:"xmlns:ct,attr"`
	NSxsi      string            `xml:"xmlns:xsi,attr"`
	MarketDir  cpMarketDir12XML  `xml:"cp:MarketParticipantDirectory"`
	ProcessDir cpProcessDir12XML `xml:"cp:ProcessDirectory"`
}

type cpMarketDir12XML struct {
	DocumentMode  string             `xml:"DocumentMode,attr"`
	Duplicate     string             `xml:"Duplicate,attr"`
	SchemaVersion string             `xml:"SchemaVersion,attr"`
	RoutingHeader cpRoutingHeaderXML `xml:"ct:RoutingHeader"`
	Sector        string             `xml:"ct:Sector"`
	MessageCode   string             `xml:"cp:MessageCode"`
}

type cpProcessDir12XML struct {
	MessageID      string           `xml:"ct:MessageId"`
	ConversationID string           `xml:"ct:ConversationId"`
	ProcessDate    string           `xml:"ct:ProcessDate"`
	MeteringPoint  string           `xml:"ct:MeteringPoint"`
	Extension      *cpExtension12XML `xml:"cp:Extension,omitempty"`
}

type cpExtension12XML struct {
	DateTimeFrom      string `xml:"cp:DateTimeFrom,omitempty"`
	DateTimeTo        string `xml:"cp:DateTimeTo,omitempty"`
	AssumptionOfCosts bool   `xml:"cp:AssumptionOfCosts"`
}

// ── CPRequest 01.12 (ANFORDERUNG_ECP / EC_PODLIST) ───────────────────────────
//
// EC_PODLIST requests the current list of registered Zählpunkte (meter points)
// from the Netzbetreiber using CPRequest 01.12 with MessageCode ANFORDERUNG_ECP.
// The MeteringPoint in ProcessDirectory is set to the ECID (Gemeinschafts-ID),
// not an individual meter point. No Extension element is required.

// PODListParams holds parameters for a PODList (Zählpunktliste) request.
type PODListParams struct {
	From           string // sender ECNumber (EEG's MarktpartnerID)
	To             string // receiver ECNumber (Netzbetreiber)
	MessageID      string // UUID; hyphens are stripped automatically
	ConversationID string // UUID; hyphens are stripped automatically
	ECID           string // Gemeinschafts-ID (used as MeteringPoint in XML)
}

// BuildPODList builds a CPRequest 01.12 message with MessageCode=ANFORDERUNG_ECP
// for requesting the current Zählpunktliste (EC_PODLIST) from the Netzbetreiber.
func BuildPODList(p PODListParams) (string, error) {
	if p.From == "" {
		return "", fmt.Errorf("From (Marktpartner-ID) is required")
	}
	if p.To == "" {
		return "", fmt.Errorf("To (Netzbetreiber-ID) is required")
	}
	if p.ECID == "" {
		return "", fmt.Errorf("ECID (Gemeinschafts-ID) is required")
	}
	if p.MessageID == "" || p.ConversationID == "" {
		return "", fmt.Errorf("MessageID and ConversationID are required")
	}

	// ct:GroupingId pattern: [0-9A-Za-z]* — hyphens not allowed, max 35 chars
	msgID  := strings.ReplaceAll(p.MessageID, "-", "")
	convID := strings.ReplaceAll(p.ConversationID, "-", "")
	if len(msgID) > 35 {
		msgID = msgID[:35]
	}
	if len(convID) > 35 {
		convID = convID[:35]
	}

	now := time.Now()
	doc := cpRequest12XML{
		NS:    cpRequest12NS,
		NSct:  cpCommonNS,
		NSxsi: xsiNS,
		MarketDir: cpMarketDir12XML{
			DocumentMode:  "PROD",
			Duplicate:     "false",
			SchemaVersion: cpSchemaVer12,
			RoutingHeader: cpRoutingHeaderXML{
				Sender:                   cpMessageAddressXML{AddressType: "ECNumber", Value: p.From},
				Receiver:                 cpMessageAddressXML{AddressType: "ECNumber", Value: p.To},
				DocumentCreationDateTime: formatDocCreationDateTime(now),
			},
			Sector:      "01",
			MessageCode: "ANFORDERUNG_ECP",
		},
		ProcessDir: cpProcessDir12XML{
			MessageID:      msgID,
			ConversationID: convID,
			ProcessDate:    now.Format(cpDateLayout),
			MeteringPoint:  p.ECID,
			// No Extension needed for ANFORDERUNG_ECP
		},
	}

	out, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("xml.Marshal: %w", err)
	}
	return xml.Header + string(out), nil
}
