ALTER TABLE members
  ADD COLUMN IF NOT EXISTS strasse TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS plz     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ort     TEXT NOT NULL DEFAULT '';
